### ISSUE TITLE
Some Errors with 0.7.1 react-native release.

### ISSUE THREAD

**Issue by piyushchauhan2011** [corymsmith/react-native-icons#68]
```
Unable to resolve module EdgeInsetsPropType from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module NativeMethodsMixin from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module NativeModules from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ReactPropTypes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ImageResizeMode from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ImageStylePropTypes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module React from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ReactNativeViewAttributes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module StyleSheet from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module StyleSheetPropType from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module createReactNativeComponentClass from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module flattenStyle from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module insetsDiffer from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module invariant from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module merge from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module warning from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module deepDiffer from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module EdgeInsetsPropType from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module NativeMethodsMixin from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module NativeModules from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ReactPropTypes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ImageResizeMode from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ImageStylePropTypes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module React from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module ReactNativeViewAttributes from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module StyleSheet from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module StyleSheetPropType from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module createReactNativeComponentClass from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module flattenStyle from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module insetsDiffer from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module invariant from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module merge from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module warning from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module deepDiffer from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-icons/FAKIconImage.ios.js
```

**Comment by corymsmith** [comment]
What version of react-native-icons? 0.2.0 should resolve this

**Comment by piyushchauhan2011** [comment]
I'm still getting error, using 0.2.0 version.

![screen shot 2015-07-17 at 1 44 29 pm](https://cloud.githubusercontent.com/assets/693487/8740277/0b55136c-2c8a-11e5-9da7-2372ec7718a4.png)

**Comment by piyushchauhan2011** [comment]
Also these are just warning in console, the icons work perfectly in the app :+1:

**Comment by steve-ng** [comment]
getting this error on new project of react-native 0.7.1

app still work fine

**Comment by josebalius** [comment]
+1 getting the same errors even after 0.2.0

**Comment by akishek22** [comment]
+1

**Comment by akiran** [comment]
+1 I am also getting this error

**Comment by admmasters** [comment]
Same error here with 0.2.0. This is due to dependence on React Native internal modules, essentially private API, that should not have leaked out and unfortunately a number of developers have used them, meaning we will need to refactor to prevent possible breakage in the future.

**Comment by corymsmith** [comment]
@jeffreywescott and I have fixed a bunch of these warnings but some modules aren't exposed externally so we will need to sort out the best way to correct that. If anyone has some thoughts or wants to do a PR it would be much appreciated :)

**Comment by admmasters** [comment]
@corymsmith and @jeffreywescott  - great job - a number of the warnings have gone. Will have a look at the React Native source and see if I come up with anything helpful.

**Comment by jeffreywescott** [comment]
One other thing I noticed ... there is a similar project (react-native-vector-icons) that seems to work without warnings. Perhaps pool efforts?

**Comment by admmasters** [comment]
Ok - I've reviewed the warnings some more can be worked around. For instance it seems invariant is being used as an assert in the following example:

```
invariant(style, "style must be initialized");
```

We probably don't need to rely on invariant here and either shim an assert or maybe use one of the many similar libraries on npm. Alternatively just throw a javascript error if style doesn't exist for instance. It might be worth breaking this down into sub tasks for each remaining warning? Just my input :-)

**Comment by corymsmith** [comment]
@admmasters Awesome thanks, if you make some tweaks just shoot me a PR and I'll review

**Comment by corymsmith** [comment]
I've just removed more of the warnings with the latest release, the only warning left is for the usage of the merge modules.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by piyushchauhan2011** [comment]
Only `merge` warning remains.

```
Unable to resolve module merge from /Users/kartikeychauhan/Documents/testcodes/react-native-test/Docit/node_modules/react-native-icons/SMXIconImage.ios.js
Unable to resolve module merge from /Users/kartikeychauhan/Documents/testcodes/react-native-test/Docit/node_modules/react-native-icons/SMXLoadingImage.ios.js
```

**Comment by admmasters** [comment]
PR created to close this off.

**Comment by corymsmith** [comment]
Thanks to @admmasters for the PR's to help close this off, just pushed 0.3.3 to NPM.

**Comment by piyushchauhan2011** [comment]
:+1:
